### ISSUE TITLE
Zustände anpassen damit 23 * 0 funktioniert

### ISSUE THREAD

**Issue by lederjan** [Little-Silver/TuringMachine#3]
![grafik](https://user-images.githubusercontent.com/79640475/116282517-29e37f80-a78b-11eb-98a2-d59adf0e4e40.png)

**Comment by Little-Silver** [comment]
![image](https://user-images.githubusercontent.com/59480521/116295245-2a831280-a799-11eb-9bf4-2bad594604e9.png)
